---
- name: Setting Docker
  hosts: all
  gather_facts: true
  become: true
  tasks:
  - name: Install docker
    yum:
      name='docker'
      state=present

  - name: Starting Docker
    service:
      name=docker
      state=started
      enabled=yes

  - name: ec2-user to docker group
    user:
      name: ec2-user
      groups: docker
      append: yes

  - name: Installing pip
    yum:
      name='python-pip'
      state=present

  - name: Install docker-py
    pip: name=docker-py

  - name: Ensure docker-compose is installed and available
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.7.0-rc1/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
      dest: /usr/bin/docker-compose
      mode: 'u+x,g+x'

  - name: Jenkins Blue Ocean
    docker_container:
      name: jenkins_blueocean
      state: started
      image: jenkinsci/blueocean
      pull: true
      ports:
        - "8888:8080"
        - "50000:50000"

  - name: Jenkins Initial password
    shell: docker exec -it jenkins_blueocean cat /var/jenkins_home/secrets/initialAdminPassword
    changed_when: false
    register: jenkinspasswd
  - name: Print Password
    debug:
      var: jenkinspasswd.stdout_lines

#- name: Docker Login
#  docker_login:
#    email: "EMAIL"
#    username: "USERNAME"
#    paswweord: "PASSWORD"
