---

- name: Download Terraform
  get_url:
   url: https://releases.hashicorp.com/terraform/{{ tf_ver }}/terraform_{{ tf_ver }}_linux_amd64.zip
   dest: /tmp

- name: Unzip Terraform
  unarchive: 
    src: /tmp/terraform_{{ tf_ver }}_linux_amd64.zip
    dest: /usr/bin
    copy: no

- name: Download Terraform Inventory
  get_url:
   url: https://github.com/adammck/terraform-inventory/releases/download/{{ tfi_ver }}/terraform-inventory_{{ tfi_ver }}_linux_amd64.zip
   dest: /tmp

- name: Unzip Terraform Inventory
  unarchive: 
    src: /tmp/terraform-inventory_{{ tfi_ver }}_linux_amd64.zip
    dest: /usr/bin
    copy: no
