---

- name: Download Terraform
  get_url:
   url: https://releases.hashicorp.com/terraform/{{ tf_ver }}/terraform_{{ tf_ver }}_linux_amd64.zip
   dest: /tmp

#- name: Sleep for 30 seconds and continue with play
#  wait_for: timeout=30

- name: Unzip Terraform
  unarchive: 
    src: /tmp/terraform_{{ tf_ver }}_linux_amd64.zip
    dest: /usr/bin
    copy: no